### ISSUE TITLE
Can We add zoom functionality ? Is it possible ?

### ISSUE THREAD

**Issue by KrLikeblue** [adamwulf/JotUI#11]
Hello Adam,

Can We add zooming feature so that user can draw with perfection ? What we will have to do to achieve zooming functionality ?

Waiting for your answer.

thanks.

**Comment by adamwulf** [comment]
For Loose Leaf, I found the best way to handle zoom was to set a transform on the view itself. Don't resize the frame to change the size, but just setting a CGAffineScaleTransform from a pan gesture works great.

**Comment by KrLikeblue** [comment]
Ok, I will try...
