### ISSUE TITLE
Can We increase number of undo/redo actions ?

### ISSUE THREAD

**Issue by KrLikeblue** [adamwulf/JotUI#12]
Hello Adam :)

I was doing undo/redo actions and those functions are limited, I think upto 10 undo actions

So Can we increase the limit for that ?

Can you let me know where I will have to change.

Thanks.

**Comment by adamwulf** [comment]
You can change that to any number you like in JotViewState.m. The constant is at the top of that file: `kJotDefaultUndoLimit`

**Comment by KrLikeblue** [comment]
Thanks Adam :)
