### ISSUE TITLE
New textures

### ISSUE THREAD

**Issue by TGWC** [adamwulf/JotUI#16]
How to add new textures, for example a crayon texture, a marker texture, a colouring pencil, a pencil, a pen ?

It's possible ?

Also, it's possible to create a video from the whole painting? This is, do you have the history of all action, and its possible to create a video from it ? Like in Brushes app, if you now it :)

**Comment by adamwulf** [comment]
It's possible - checkout JotHighlighterBrushTexture.m for an example of how to create a texture from a UIImage to use as a brush.

For the video, i'm there's nothing built in to help, so you'd potentially have to save and replay the actions yourself. another option would be to use [ReplayKit](https://developer.apple.com/reference/replaykit) to record and replay the drawing.
