### ISSUE TITLE
failed to make complete framebuffer object 8cd6

### ISSUE THREAD

**Issue by sosolo0307** [adamwulf/JotUI#17]
Thank you for creating a really good library.

I made a big size view.(2,300, 1800)
However, the following situation has occurred :
How can I solve this problem?

**Comment by adamwulf** [comment]
is that resolution in pts or px? I've tested up to the px size of the iPad Pro (2732 x 2048px, 1368 x 1024pt). I suspect you're above the max allowed texture size for the device, which I believe is around 2048 pts)

**Comment by sosolo0307** [comment]
You're right.
I did not know the max allowed texture size for the device. That the maximum size of texture is 2048. When I think of the size, I realize that the size of texture is too big for me, so how should I handle it?
And is there a way to make a larger Canvas using a bunch of smaller texture?

**Comment by adamwulf** [comment]
There are two options that I can think of. The first would be to create a 2nd JotView and layout next to the first. This'll be tricky to handle drawing strokes that cross that boundary, but theoretically is possible.

The second option would be to create a JotView with the correct width/height ratio, then use a transform to scale the JotView's texture to the correct visible size.

**Comment by sosolo0307** [comment]
Thank you for your kind reply.
I thought you'd do it as well as you told me.
Of course I'm not convinced of myself, but I'm more confident when I hear your words.
I think the first method would be much better than the second one.
I guess there's a lot of work to do, but I think it's worth challenging.

The first method didn't seem to be able to produce prototypes quickly, so I tried to test them in the second way.
Moreover, the performance was worse than expected, and the quality was poor.
Of course I can't make it because I can't make it, but I want to improve it. 
I'll try to make lots of attempts.

Of course I haven't even understood your code yet.

Thank you !

**Comment by adamwulf** [comment]
good luck and lmk what you end up with! i'll close out this issue, but feel free to open another as questions arise
