### ISSUE TITLE
Why does the drawing look like trash?

### ISSUE THREAD

**Issue by snapchatdotcom** [adamwulf/JotUI#20]
Like look at dis. It looks really soft n stuff.
![img_0067](https://cloud.githubusercontent.com/assets/21147741/24424030/f52fea0e-13b3-11e7-89f1-8289f2af805c.PNG)

**Comment by adamwulf** [comment]
Tap the Settings button and play around with some of the options there. There's additional options to tweak in the code that aren't in the settings as well, but that'll show more of the possibility.

![simulator screen shot mar 28 2017 2 49 07 pm](https://cloud.githubusercontent.com/assets/251087/24424327/de4829a2-13c5-11e7-82ed-8d88e157e090.png)
