### ISSUE TITLE
palm rejection?

### ISSUE THREAD

**Issue by snapchatdotcom** [adamwulf/JotUI#21]
when I draw with my hand resting on the iPad, it either draws at my palm AND the point on which I'm drawing, or it glitches out and erases what I was drawing on that point (and draws a little of what was drawn where my palm was.

**Comment by adamwulf** [comment]
Since the Apple Pencil has such good built-in palm rejection, I decided not to add terribly much more logic on top of that. However - you'll likely get better results if you rest your palm firmly on the screen, instead of trying to hover gently over the screen - i've found that helps a bit.
