### ISSUE TITLE
How to make pen stroke as clear and sharp as loose-leaf?

### ISSUE THREAD

**Issue by OrcaData** [adamwulf/JotUI#37]
Thanks for the great work.

I found that the pen at JotUI Example is blurry even I set Alpha to 1 and increase width. However, I found that pen(the second thinker pen) at loose-leaf is very sharp and clear with pure black color. Is there a way to adjust it? Many thanks.

**Comment by adamwulf** [comment]
Haven't had a chance to look at this, but seems you were able to figure it out. For anyone else potentially hitting the same problem, what was the issue?

**Comment by OrcaData** [comment]
Thanks, Adam. I solved it by changing stepWidthForStroke to 0.5 instead of 2, and the stroke looks great.
 - (CGFloat)stepWidthForStroke {
    return .5;
}

**Comment by adamwulf** [comment]
Awesome thanks - I've pushed up that same change so others will get the crisper lines as well :)
