### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIView contentScaleFactor]

### ISSUE THREAD

**Issue by abrpatel** [adamwulf/JotUI#43]
getting this error when I call the export function. I can't seem to resolve it. The export itself works fine though.

**Comment by adamwulf** [comment]
It's only logged to console, right? or is it also throwing an exception and stopping execution?

that's an unfortunate bug from long ago before they started logging that error

**Comment by abrpatel** [comment]
In production mode, it works fine, and saves and returns the image with no issues. In development mode, the first time you save, it slows the save process and actually points to the issue. I'm afraid that it might be a cause for rejection if I use the framework in the app when I submit an update with it.

**Comment by adamwulf** [comment]
For what it's worth, no one has sent me anything about it getting rejected, and it's currently this way in Loose Leaf which is still in the store. I last updated Loose Leaf on Jan 22, 2019, and it was approved then w/ JotUI.

**Comment by abrpatel** [comment]
Sounds good! I'll reopen the issue if anything does happen during review. Thanks!

**Comment by abrpatel** [comment]
The issue actually causes a memory leak, at every time you export.

**Comment by adamwulf** [comment]
well that's no good - which objects are leaking? does it leak in the included example app during export?

**Comment by abrpatel** [comment]
Testing now. Will let you know.

**Comment by abrpatel** [comment]
<img width="1063" alt="Screen Shot 2019-05-13 at 1 13 31 PM" src="https://user-images.githubusercontent.com/947100/57644072-f056e100-7580-11e9-978e-17fb6d6b9e11.png">

Add this to the jotuiexample in the info.plist file
<key>NSPhotoLibraryAddUsageDescription</key>
<string>Our application needs permission to write photos...</string>

now run instruments and draw something. press settings and click save, you get the above results. Leaks aren't even captured, it just freezes.

**Comment by adamwulf** [comment]
Ok thanks, i'll check it out. it'll likely be a few days before i'll have time to get to it

**Comment by abrpatel** [comment]
No worries. Just let me know, I'll test and commit the NSData feature as well, as I'll make sure that code doesn't leak before submitting the PR for it.

**Comment by abrpatel** [comment]
Fixed issue in PR. It was a simple matter of placement.
