### ISSUE TITLE
Not running in my iPhone

### ISSUE THREAD

**Issue by KrLikeblue** [adamwulf/JotUI#7]
When  I try to run your project in  my iPhone. It says

My iPhone doesn’t match any of jotuiexample.app’s targeted device families. You can expand jotuiexample.app’s targeted device families to support your iPhone.

Any idea ?

Thanks

**Comment by adamwulf** [comment]
Just pushed up a commit on master that adds an iPhone UI :)

**Comment by KrLikeblue** [comment]
Worked :) 👍

**Comment by KrLikeblue** [comment]
Can you add more brushes please ? 

Or can you tell me how to achieve other brush strokes apart from pen and marker ?
Your tool is really awesome.

Thanks

**Comment by adamwulf** [comment]
glad you're enjoying it! :)

I won't have time to add any new brushes in the near future, hopefully I'll get to it in the new year. To get started on your own brushes, take a look at the Pen, Marker, and Eraser classes in the jotuiexample project. Those are the classes that define the current behavior. Just experiment with those and you'll be able to come up with some interesting stuff :)
